### get all persons (MongoDB)
GET http://localhost:3001/api/persons

### Add person (MongoDB)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Marcio",
  "number": "98272878237"
}